<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationTitle>Netshare</ApplicationTitle>
    <Product>Netshare</Product>
    <AssemblyName>Netshare</AssemblyName>
    <RootNamespace>EasyShare.Desktop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyShare.Protocol\EasyShare.Protocol.csproj" />
  </ItemGroup>

</Project>
